# Generated by Django 5.2.5 on 2025-08-27 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course_type', models.CharField(choices=[('dance', 'Dance'), ('drawing', 'Drawing')], max_length=50)),
                ('sarvabharatiya_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_date', models.DateField()),
                ('total_fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.student')),
            ],
        ),
    ]
